### PR TITLE
Replace custom message with std geometry_sgs/Twist and split joystick/head control in two separate messages.

### PR DESCRIPTION
**Pull request by wuehr1999**
Hi @aentinger,
I implemented the option to publish a twist message as suggested in #5.
The left joystick controls linear velocities in x- and y-direction. The right joystick controls the angular rotation speed around the z-axis. There can also be maximum values configured for those values.
The corresponding launch configuration is not in the /l3xz namespace to provide a simple publisher for the typical /cmd_vel message. With this setup, the teleop node can also be adapted to other (standard) platforms easily.
If You agree, I will proceed with updating the documentation in the README.md

### CODE REVIEW

**Comment by aentinger** [comment]
Hi @wuehr1999 :coffee: :wave:

Thank you very much for your contribution. However, I do not want to support both custom build message and Twist message at the same time (that would be a maintenance nightmare). You've convinced me, let's go for geometry_msgs::Twist. Please remove anything related to the custom teleop message.

However, what I am missing right now, is the ability to also control the joystick. This could be done via the directional pad of the PS3 joystick and another Twist message. What do you think?

**Comment by wuehr1999** [comment]
Hi @aentinger, this sound like an idea that will fit. I will do it that way.

**Comment by wuehr1999** [comment]
Hi @aentinger 
I implemented two messages now. The first one contains linear x and y from the directional pad. The second contains linear x and y and angular x and z from the joysticks. This seems reasonable for me to cover the most usecases.

**Comment by aentinger** [comment]
Hi @wuehr1999 :coffee: :wave:

I took the liberty to make a couple of changes. Ultimately I do believe that there is a trade-off between to be found between a generic teleoperation node and one tailored towards L3X-Z: what makes sense for a hexapod robot does not necessarily make sense for a wheeled robot and vice-versa. If you want to serve your own application plz consider forking this repository and adjusting the joystick-2-message assignment as you see fit.

Note: It would be great if the the teleoperation of the head would have a finer-grained control than ON/OFF. I thought the PS3-Joystick supported "axis" output even on the buttons, but the Linux joystick driver does not support this. Any idea why?

**Pull request merged**
